In [1]:
import pandas as pd
import torch
from transformers import BertTokenizer, BertModel
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import numpy as np
# Load a CSV file into a DataFrame

In [2]:
df = pd.read_csv('IMDB-Movie-Dataset(2023-1951).csv')

print(df.head())

   Unnamed: 0    movie_id                       movie_name  year  \
0           0  tt15354916                            Jawan  2023
1           1  tt15748830                       Jaane Jaan  2023
2           2  tt11663228                           Jailer  2023
3           3  tt14993250  Rocky Aur Rani Kii Prem Kahaani  2023
4           4  tt15732324                            OMG 2  2023

                   genre                                           overview  \
0       Action, Thriller  A high-octane action thriller which outlines t...
1  Crime, Drama, Mystery  A single mother and her daughter who commit a ...
2  Action, Comedy, Crime  A retired jailer goes on a manhunt to find his...
3  Comedy, Drama, Family  Flamboyant Punjabi Rocky and intellectual Beng...
4          Comedy, Drama  An unhappy civilian asks the court to mandate ...

            director                                               cast
0              Atlee  Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ...
1        Sujoy Ghosh  Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ...
2  Nelson Dilipkumar  Rajinikanth, Mohanlal, Shivarajkumar, Jackie S...
3        Karan Johar  Ranveer Singh, Alia Bhatt, Dharmendra, Shabana...
4           Amit Rai  Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa...

In [3]:
# List all column names
print("Columns in the DataFrame:")
print(df.columns.tolist())

Columns in the DataFrame:
['Unnamed: 0', 'movie_id', 'movie_name', 'year', 'genre', 'overview', 'director', 'cast']

In [4]:
# To See Unique genres
# Split genres into lists and clean up whitespace
df['genre_list'] = df['genre'].str.split(',').apply(lambda x: [genre.strip() for genre in x])

# Explode the genre lists into separate rows
genres_exploded = df.explode('genre_list')

# Get unique genres
unique_genres = genres_exploded['genre_list'].unique()

# Count total unique genres
total_unique_genres = len(unique_genres)
print("Total unique genres:", total_unique_genres)

# Display unique genres
print("\nList of unique genres:")
for genre in unique_genres:
    print(genre)

Total unique genres: 20

List of unique genres:
Action
Thriller
Crime
Drama
Mystery
Comedy
Family
Adventure
Fantasy
History
Musical
Biography
Horror
Romance
Sport
Sci-Fi

Music
Animation
War

In [5]:
df['genre'] = df['genre'].str.strip()
missing_genre_rows = df[df['genre'].isnull() | (df['genre'] == '')]
print("Missing values in the genre column  : " , len(missing_genre_rows))

df = df.dropna(subset=['genre'])  # Remove rows with NaN values in 'genre' column
df = df[df['genre'] != '']  # Remove rows where 'genre' is an empty string
 # Check the number of remaining rows

Missing values in the genre column  :  18

In [6]:
df['genre'] = df['genre'].str.strip()
missing_genre_rows = df[df['genre'].isnull() | (df['genre'] == '')]
print(len(missing_genre_rows))

0

In [7]:
# To See Unique genres
# Split genres into lists and clean up whitespace
df['genre_list'] = df['genre'].str.split(',').apply(lambda x: [genre.strip() for genre in x])

# Explode the genre lists into separate rows
genres_exploded = df.explode('genre_list')

# Get unique genres
unique_genres = genres_exploded['genre_list'].unique()

# Count total unique genres
total_unique_genres = len(unique_genres)
print("Total unique genres:", total_unique_genres)

# Display unique genres
print("\nList of unique genres:")
for genre in unique_genres:
    print(genre)

Total unique genres: 19

List of unique genres:
Action
Thriller
Crime
Drama
Mystery
Comedy
Family
Adventure
Fantasy
History
Musical
Biography
Horror
Romance
Sport
Sci-Fi
Music
Animation
War

In [8]:
# Count the number of rows where the 'overview' column is either "Add a Plot" or "Plot under wraps"
add_plot_count = df[df['overview'] == 'Add a Plot'].shape[0]
plot_under_wraps_count = df[df['overview'] == 'Plot under wraps'].shape[0]

print(f"Number of 'Add a Plot' entries in 'overview' column: {add_plot_count}")
print(f"Number of 'Plot under wraps' entries in 'overview' column: {plot_under_wraps_count}")

Number of 'Add a Plot' entries in 'overview' column: 65
Number of 'Plot under wraps' entries in 'overview' column: 1

In [9]:
# Remove rows where the 'overview' column is "Add a Plot" or "Plot under wraps"
df = df[~df['overview'].isin(['Add a Plot', 'Plot under wraps'])]

# Verify the removal
print(f"Remaining rows after removal: {len(df)}")

Remaining rows after removal: 2115

In [10]:
# Count the number of rows where the 'overview' column is either "Add a Plot" or "Plot under wraps"
add_plot_count = df[df['overview'] == 'Add a Plot'].shape[0]
plot_under_wraps_count = df[df['overview'] == 'Plot under wraps'].shape[0]

print(f"Number of 'Add a Plot' entries in 'overview' column: {add_plot_count}")
print(f"Number of 'Plot under wraps' entries in 'overview' column: {plot_under_wraps_count}")

Number of 'Add a Plot' entries in 'overview' column: 0
Number of 'Plot under wraps' entries in 'overview' column: 0

In [11]:
df = df.dropna().reset_index(drop=True)

In [12]:
# Load the pre-trained BERT tokenizer and model with explicit clean_up_tokenization_spaces setting
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', clean_up_tokenization_spaces=True)
model = BertModel.from_pretrained('bert-base-uncased')

In [13]:
def generate_movie_embedding(description):
    # Tokenize the movie description
    inputs = tokenizer(description, return_tensors="pt", padding=True, truncation=True, max_length=512)
    
    # Get the embeddings from BERT
    outputs = model(**inputs)
    
    # Average the token embeddings to get a single movie embedding (you can also use other methods)
    embeddings = outputs.last_hidden_state.mean(dim=1)  # Average across tokens
    return embeddings

In [14]:
unique_genres = df['genre'].unique()

# Create a dictionary that maps each genre to an index
genre_to_index = {genre: idx for idx, genre in enumerate(unique_genres)}

# Step 2: One-hot Encoding for Genres
def generate_genre_embedding(genres, genre_to_index):
    # Create a zero vector of size equal to the number of unique genres
    genre_vector = np.zeros(len(unique_genres))  
    
    # Set the corresponding index to 1 for each genre
    for genre in genres:
        genre = genre.strip()  # Remove any extra spaces from the genre
        genre_index = genre_to_index.get(genre)  # Get the index for the genre
        if genre_index is not None:
            genre_vector[genre_index] = 1
    
    # Reshape the genre_vector to ensure it's a 2D array
    genre_embedding = genre_vector.reshape(1, -1)
    
    return genre_embedding

In [15]:
# Step 1: Compute Overview Embeddings
overview_embeddings = []

for i, row in df.iterrows():
    description = row['overview']  # Assuming 'overview' contains the movie description
    
    # Get the movie description embedding
    embedding = generate_movie_embedding(description)
    embedding = embedding.detach().numpy().reshape(1, -1)  # Ensure it's 2D
    
    overview_embeddings.append(embedding)

# Convert the list of overview embeddings into a NumPy array
overview_embeddings = np.vstack(overview_embeddings)

# Step 2: Apply PCA to Overview Embeddings
# Standardize the overview embeddings before PCA
scaler_overview = StandardScaler()
overview_embeddings_standardized = scaler_overview.fit_transform(overview_embeddings)

# Apply PCA to reduce dimensionality of overview embeddings
pca_overview = PCA(n_components=300)  # Retain 100 components or adjust as needed
reduced_overview_embeddings = pca_overview.fit_transform(overview_embeddings_standardized)

# Verify the shape and explained variance
print("Original shape of overview embeddings:", overview_embeddings.shape)
print("Reduced shape of overview embeddings:", reduced_overview_embeddings.shape)
print("Explained Variance (Overview, first 10 components):", pca_overview.explained_variance_ratio_[:10])
print("Total Variance Retained (Overview):", np.sum(pca_overview.explained_variance_ratio_))

# Step 3: Generate Genre One-Hot Encodings
genre_embeddings = []

for i, row in df.iterrows():
    # Get genres as a list (e.g., ['Action', 'Comedy', 'Drama'])
    genres = row['genre'].split(",")
    
    # Generate one-hot encoding for the genres
    genre_embedding = generate_genre_embedding(genres, genre_to_index)
    genre_embeddings.append(genre_embedding)


# Convert genre embeddings to a NumPy array
genre_embeddings = np.array(genre_embeddings)



# Reshape genre_embeddings to ensure it's 2D (if needed)
if genre_embeddings.ndim == 3:
    genre_embeddings = genre_embeddings.squeeze(axis=1)

# Step 4: Combine Reduced Overview Embeddings and Genre One-Hot Encodings
combined_embeddings = np.hstack((reduced_overview_embeddings, genre_embeddings))

# Verify the shape of the final movie embeddings
print("Final shape of combined movie embeddings:", combined_embeddings.shape)

Original shape of overview embeddings: (2078, 768)
Reduced shape of overview embeddings: (2078, 300)
Explained Variance (Overview, first 10 components): [0.09182159 0.06607978 0.0490037  0.03544463 0.02943625 0.02560963
 0.02455486 0.02364872 0.02141056 0.01887356]
Total Variance Retained (Overview): 0.95188034
Final shape of combined movie embeddings: (2078, 517)

In [16]:
df.head()

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast,genre_list
0,0,tt15354916,Jawan,2023,"Action, Thriller",A high-octane action thriller which outlines t...,Atlee,"Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ...","[Action, Thriller]"
1,1,tt15748830,Jaane Jaan,2023,"Crime, Drama, Mystery",A single mother and her daughter who commit a ...,Sujoy Ghosh,"Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ...","[Crime, Drama, Mystery]"
2,2,tt11663228,Jailer,2023,"Action, Comedy, Crime",A retired jailer goes on a manhunt to find his...,Nelson Dilipkumar,"Rajinikanth, Mohanlal, Shivarajkumar, Jackie S...","[Action, Comedy, Crime]"
3,3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,2023,"Comedy, Drama, Family",Flamboyant Punjabi Rocky and intellectual Beng...,Karan Johar,"Ranveer Singh, Alia Bhatt, Dharmendra, Shabana...","[Comedy, Drama, Family]"
4,4,tt15732324,OMG 2,2023,"Comedy, Drama",An unhappy civilian asks the court to mandate ...,Amit Rai,"Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa...","[Comedy, Drama]"

In [17]:
# Step 5: Add Embeddings to DataFrame
df['overview_embedding'] = list(reduced_overview_embeddings)  # Add reduced overview embeddings
df['genre_embedding'] = list(genre_embeddings)  # Add genre one-hot encodings
df['combined_embedding'] = list(combined_embeddings)  # Add combined embeddings

In [18]:
# Display the updated DataFrame
df.head()

,Unnamed: 0,movie_id,movie_name,year,genre,overview,director,cast,genre_list,overview_embedding,genre_embedding,combined_embedding
0,0,tt15354916,Jawan,2023,"Action, Thriller",A high-octane action thriller which outlines t...,Atlee,"Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ...","[Action, Thriller]","[-5.0708923, 9.435328, 0.2523424, -12.033529, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[-5.070892333984375, 9.435327529907227, 0.2523..."
1,1,tt15748830,Jaane Jaan,2023,"Crime, Drama, Mystery",A single mother and her daughter who commit a ...,Sujoy Ghosh,"Kareena Kapoor, Jaideep Ahlawat, Vijay Varma, ...","[Crime, Drama, Mystery]","[-11.981152, 0.09720064, 1.3757641, 4.408209, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...","[-11.981151580810547, 0.09720063954591751, 1.3..."
2,2,tt11663228,Jailer,2023,"Action, Comedy, Crime",A retired jailer goes on a manhunt to find his...,Nelson Dilipkumar,"Rajinikanth, Mohanlal, Shivarajkumar, Jackie S...","[Action, Comedy, Crime]","[-6.290186, 4.291925, -4.3512173, 1.4714161, -...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[-6.290185928344727, 4.291924953460693, -4.351..."
3,3,tt14993250,Rocky Aur Rani Kii Prem Kahaani,2023,"Comedy, Drama, Family",Flamboyant Punjabi Rocky and intellectual Beng...,Karan Johar,"Ranveer Singh, Alia Bhatt, Dharmendra, Shabana...","[Comedy, Drama, Family]","[4.2022715, -5.1491327, 9.279877, -3.117734, 3...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, ...","[4.202271461486816, -5.14913272857666, 9.27987..."
4,4,tt15732324,OMG 2,2023,"Comedy, Drama",An unhappy civilian asks the court to mandate ...,Amit Rai,"Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa...","[Comedy, Drama]","[-8.410875, 4.378258, -3.6146255, 3.7010746, -...","[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ...","[-8.41087532043457, 4.378258228302002, -3.6146..."

In [19]:
movie_embeddings = combined_embeddings

In [20]:
# Example user profile: User liked 'Godfather' and 'K.G.F: Chapter 1'
#input = ['Rockstar','Tumbbad']
input = ['Krrish']
#input =['Sukhee']

# Find the indices of the liked movies in the dataframe
user_movie_indices = [df[df['movie_name'] == movie].index[0] for movie in input]

# Calculate user profile by averaging the embeddings of the liked movies
user_profile = np.mean([movie_embeddings[i] for i in user_movie_indices], axis=0)

# Print the liked movie names and the user profile
print("input Movies:", input)
print("User Profile as a list:", user_profile.tolist())

user_movie_indices

input Movies: ['Krrish']
User Profile as a list: [2.8262195587158203, 2.937276840209961, -9.10635757446289, -1.2455977201461792, 7.160590648651123, -8.42646598815918, -9.456833839416504, 3.7645955085754395, -9.275101661682129, -7.332108974456787, 0.43302348256111145, -10.702631950378418, -1.5046932697296143, 3.210906505584717, 6.539816856384277, 2.7931292057037354, 2.8133156299591064, -0.8300255537033081, 3.5512566566467285, 7.1526641845703125, 3.2801318168640137, -1.5632977485656738, 4.328505992889404, 1.8529689311981201, -3.3250820636749268, -2.985689878463745, 0.8822378516197205, -1.874825358390808, -1.5486485958099365, -3.8359556198120117, 0.6635167002677917, 2.5353376865386963, -5.196525573730469, -2.462226152420044, -1.5068769454956055, 3.099778413772583, 2.3372700214385986, 0.7185608148574829, -1.9570485353469849, -2.7479748725891113, -2.0133917331695557, -0.12539134919643402, 2.0083160400390625, 2.426643133163452, -0.009363860823214054, 1.0363439321517944, -1.8689574003219604, -1.7051833868026733, -0.668968677520752, 0.4166460633277893, 1.140199065208435, 2.366933822631836, -0.6656720638275146, 2.181854009628296, -1.5561461448669434, 1.2257251739501953, 1.3772765398025513, 2.735236406326294, 0.4694216549396515, 2.0804340839385986, -4.2414069175720215, -1.2386211156845093, -0.7703200578689575, -2.882330894470215, 2.244290590286255, 1.1952924728393555, 1.5238003730773926, -2.5769400596618652, -0.18664126098155975, -0.9771543741226196, 2.6097030639648438, -2.9896585941314697, -0.38884633779525757, -0.7630957961082458, -0.36799001693725586, -1.004991054534912, 0.009200099855661392, -0.3733583390712738, -0.8314498066902161, 5.704414367675781, -0.3223329186439514, -2.799755334854126, -1.9096155166625977, 1.1018856763839722, 3.942697525024414, 1.2828056812286377, 2.9108943939208984, -1.0076377391815186, -1.6372075080871582, -1.338590383529663, 1.0537633895874023, -0.7940527200698853, 1.6796624660491943, 0.7858483195304871, -0.2797667384147644, 1.0989238023757935, -1.157859444618225, 1.0916439294815063, -0.8765013217926025, -0.5279936790466309, 0.6119692921638489, 1.231369972229004, -1.1941035985946655, 2.826119899749756, -0.3053686022758484, 0.9388485550880432, 0.03779586777091026, 1.6091688871383667, -0.5267688035964966, 1.8264580965042114, -0.9292183518409729, 2.3848276138305664, 0.5044450759887695, -0.565096914768219, -0.24055969715118408, -1.1344308853149414, 1.101349949836731, -0.36992278695106506, 1.4904502630233765, -1.1585874557495117, 0.1768583208322525, -3.2115671634674072, -2.588207244873047, 0.8878783583641052, -1.7622708082199097, -0.8225244283676147, -0.8524587154388428, -2.818729877471924, -1.1945043802261353, 0.0020021582022309303, -0.11792764067649841, -1.0248284339904785, -0.11608516424894333, -0.32546842098236084, 0.7042288184165955, 0.7242647409439087, 0.7479155659675598, 2.873600959777832, 2.2473464012145996, -0.2226155400276184, -0.036482952535152435, -0.5321794748306274, -0.5641613006591797, -1.4784713983535767, 0.9833266139030457, -0.6602868437767029, 1.3555766344070435, 0.8947777152061462, -0.005518738180398941, 0.2589512765407562, 0.8391024470329285, 1.061276912689209, 0.3371466398239136, 0.2736715078353882, -0.23832936584949493, 1.0691615343093872, 1.5956286191940308, 1.003521203994751, -0.09671181440353394, -0.776261031627655, 0.06672969460487366, 2.1824746131896973, 2.025331497192383, 1.1555224657058716, 0.5336303114891052, 0.7437224984169006, -1.8220927715301514, 1.9734543561935425, 0.8645967841148376, 1.8559284210205078, 1.4969494342803955, -1.146405816078186, 0.2777835428714752, -0.5095666646957397, -0.7089794874191284, 1.6426358222961426, -1.6530144214630127, 0.7370057702064514, -0.06916138529777527, -2.2064428329467773, -0.075703464448452, -0.1860671043395996, -0.1916189044713974, 0.1470368504524231, 1.4244085550308228, -0.24636878073215485, 1.3562414646148682, -0.26838576793670654, -0.11947285383939743, -0.4371264576911926, -0.3955501914024353, 0.2126903235912323, -2.0975663661956787, 0.3493933379650116, -1.5678637027740479, -0.7835728526115417, 0.9125255346298218, 1.118287444114685, 0.8681834936141968, 0.12470448762178421, 1.2715216875076294, 1.3999383449554443, -0.9565644264221191, 0.43198975920677185, 0.28312891721725464, -0.6750415563583374, 0.26865291595458984, -0.05467541143298149, 0.9777573943138123, 0.4311942756175995, -0.6735410690307617, 0.6526303291320801, 0.45869606733322144, -0.1635444611310959, -1.1419728994369507, -1.0821675062179565, 0.8028302788734436, 0.18609122931957245, 0.02189572900533676, -0.24629053473472595, -0.40311023592948914, 0.08878446370363235, -0.5484529733657837, -0.25937381386756897, 0.7070630788803101, -0.8354884386062622, -0.4974527657032013, 0.5152369141578674, -0.04039374738931656, 0.8141472935676575, -0.5305135846138, -0.08132125437259674, 0.308398574590683, 0.49055615067481995, -0.516382098197937, -0.729922890663147, -0.6248466372489929, -0.45417049527168274, -0.12847787141799927, -0.09986884891986847, -0.8482558131217957, 0.37245070934295654, 0.4058155417442322, -0.07335840165615082, -1.3811148405075073, -0.6049683094024658, -0.7251700758934021, 2.018266439437866, -0.2604467272758484, -0.4566785395145416, 0.826856791973114, 0.4007199704647064, -0.08160600066184998, -0.06329029053449631, -0.6659700870513916, -0.3593408167362213, 0.054468490183353424, -0.029126275330781937, -0.7221457362174988, 0.4181426763534546, 0.03414210304617882, -0.5062702298164368, -1.3174389600753784, -0.6029930710792542, -0.7020717859268188, 0.24121487140655518, 0.041714731603860855, -0.3467941880226135, 0.0798565000295639, -0.9527456164360046, 0.489803284406662, -0.491928368806839, -0.5218167901039124, 0.04310214892029762, 0.5374077558517456, -0.015031540766358376, -0.5701871514320374, 0.20163007080554962, 0.96213299036026, -0.493644654750824, 0.6340306401252747, 0.15375415980815887, 0.7104073762893677, 0.3732488453388214, -0.2609059810638428, 0.1583087146282196, 0.4735458791255951, 0.5335873961448669, 0.9890576601028442, -0.5994125008583069, 0.10580817610025406, 0.7696590423583984, 0.16384238004684448, 0.8538815379142761, -1.2420566082000732, 0.24775606393814087, -0.6336815357208252, 0.7248306274414062, -0.3012552559375763, 0.08315874636173248, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[296]

In [21]:
liked_movies = df['movie_name'][user_movie_indices].tolist()

# Print the movie names
print("Movies given:", liked_movies)

Movies given: ['Krrish']

In [22]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

k = 10+len(input)  # Number of nearest neighbors you want to find
knn = NearestNeighbors(n_neighbors=k, metric='cosine')  # Use cosine distance for similarity

# Step 2: Fit the model with all movie embeddings (no filtering yet)
knn.fit(movie_embeddings)

# Step 3: Find the k nearest neighbors to the user profile
distances, indices = knn.kneighbors(user_profile.reshape(1, -1), n_neighbors=k)

# Step 4: Get the recommended movie names using the indices from the original movie embeddings
recommended_movies = df.iloc[indices.flatten()]['movie_name']

# Step 5: Remove the liked movies from the recommendations
filtered_recommendations = [movie for movie in recommended_movies if movie not in liked_movies]

# Step 6: Display the top recommended movies (after filtering out the liked ones)
print("Recommended Movies:", filtered_recommendations)

Recommended Movies: ['A Flying Jatt', 'Bhavesh Joshi Superhero', 'Brahmastra Part One: Shiva', 'Mr. X', 'Om - The Battle Within', 'Krrish 3', 'Commando 2', 'Street Fighter: The Legend of Chun-Li', 'Ganapath', 'Kalki 2898-AD']

In [23]:
# List of user liked movies
user_liked_movies = liked_movies

# Initialize an empty list to store the genres of user liked movies
user_movie_genres = []

# Loop through each movie and fetch its genre(s)
for movie in user_liked_movies:
    # Find the genre(s) for the movie from the df DataFrame
    genre = df[df['movie_name'] == movie]['genre'].values
    if len(genre) > 0:
        user_movie_genres.append((movie, genre[0]))  # Get the first genre if available
    else:
        user_movie_genres.append((movie, 'Genre Not Found'))  # If no genre found

# Print the genres for each user liked movie
for movie, genre in user_movie_genres:
    print(f"Movie: {movie}, Genre: {genre}")

Movie: Krrish, Genre: Action, Adventure, Sci-Fi

In [24]:
recommended_genres = []

# Loop through each recommended movie and fetch its genres
for movie in filtered_recommendations:
    # Find the genre(s) for the movie from the df DataFrame
    genre = df[df['movie_name'] == movie]['genre'].values
    if len(genre) > 0:
        recommended_genres.append((movie, genre[0]))  # Get the first genre if available
    else:
        recommended_genres.append((movie, 'Genre Not Found'))  # If no genre found

# Print the genres for each recommended movie
for movie, genre in recommended_genres:
    print(f"Movie: {movie}, Genre: {genre}")

Movie: A Flying Jatt, Genre: Action, Adventure, Comedy
Movie: Bhavesh Joshi Superhero, Genre: Action, Crime, Drama
Movie: Brahmastra Part One: Shiva, Genre: Action, Adventure, Fantasy
Movie: Mr. X, Genre: Action, Crime, Drama
Movie: Om - The Battle Within, Genre: Action, Thriller
Movie: Krrish 3, Genre: Action, Adventure, Sci-Fi
Movie: Commando 2, Genre: Action, Adventure, Thriller
Movie: Street Fighter: The Legend of Chun-Li, Genre: Action, Crime, Fantasy
Movie: Ganapath, Genre: Action, Drama, Sci-Fi
Movie: Kalki 2898-AD, Genre: Action, Drama, Fantasy

In [25]:
recommended_genres_overview = []

# Loop through each recommended movie and fetch its genre and overview
for movie in filtered_recommendations:
    # Find the genre and overview for the movie from the df DataFrame
    movie_data = df[df['movie_name'] == movie]
    if not movie_data.empty:
        genre = movie_data['genre'].values[0]  # Get the genre
        overview = movie_data['overview'].values[0]  # Get the overview
        recommended_genres_overview.append((movie, genre, overview))
    else:
        recommended_genres_overview.append((movie, 'Genre Not Found', 'Overview Not Found'))  # If no data found

# Print the genre and overview for each recommended movie
for movie, genre, overview in recommended_genres_overview:
    print(f"Movie: {movie}, Genre: {genre},--- Overview: {overview}")

Movie: A Flying Jatt, Genre: Action, Adventure, Comedy,--- Overview: Jatt is a reluctant superhero who fights crime and protects people. He meets his match in the evil Raka, who he must vanquish to save the day.
Movie: Bhavesh Joshi Superhero, Genre: Action, Crime, Drama,--- Overview: The origin story of Bhavesh Joshi, an Indian superhero, who sets out to fulfill his slain friend's wish to clean and reform the country, by training himself to fight and wearing a mask.
Movie: Brahmastra Part One: Shiva, Genre: Action, Adventure, Fantasy,--- Overview: A DJ with superpowers and his ladylove embark on a mission to protect the Brahmastra, a weapon of enormous energy, from dark forces closing in on them.
Movie: Mr. X, Genre: Action, Crime, Drama,--- Overview: After gaining the power of invisibility; a man becomes a vigilante, in order to take revenge on those who have wronged him.
Movie: Om - The Battle Within, Genre: Action, Thriller,--- Overview: After losing his memory while fighting enemies, Om has to battle terrorists and amnesia in order to restore his father's honour after his old man was arrested for betraying his country.
Movie: Krrish 3, Genre: Action, Adventure, Sci-Fi,--- Overview: Krrish and his scientist father must save the world and their own family from an evil man named Kaal and his gang of mutants, led by the ruthless Kaya.
Movie: Commando 2, Genre: Action, Adventure, Thriller,--- Overview: Commando Karan uses his combat skills to eradicate black money, which has been siphoned to banks abroad.
Movie: Street Fighter: The Legend of Chun-Li, Genre: Action, Crime, Fantasy,--- Overview: When a child, Chun-Li sees her father being captured by wealthy gangster Bison. When she grows up, she goes into a quest for justice and bring down the criminal organization Shadaloo which is led by Bison.
Movie: Ganapath, Genre: Action, Drama, Sci-Fi,--- Overview: In a dystopian future, Ganapath, a relentless and skilled vigilante, embarks on a mission to dismantle a powerful criminal empire that has gripped the city in fear, Ganapath becomes a symbol of hope for the oppressed in which leads dark.
Movie: Kalki 2898-AD, Genre: Action, Drama, Fantasy,--- Overview: A modern-day avatar of Vishnu, a Hindu god, who is believed to have descended to earth to protect the world from evil forces.